### ISSUE TITLE
what i do ?

### ISSUE THREAD

**Issue by ghost** [4w4k3/BeeLogger#104]
These info above are correct? (y/n) :y
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 9993rills** [comment]
Hello Bro... i'm currently facing same issue, any solution so far??

**Comment by Miroteam54** [comment]
Такая же проблема. Есть идея установки более старой версии. Но еще не пробовал

**Comment by 9993rills** [comment]
Я подозреваю, что ошибка связана с "**** python -m pip install --upgrade pip ****", поскольку я все еще не могу установить правильный вариант для своего устройства - все еще запрашивает обновление даже после установки. Вы проверяли свое на то же самое? если не для вас проблемы, вы можете поделиться, как установить pip и запустить?
Спасибо!

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @9993rills @Miroteam54 @ghost

It was tested on latest kali Linux 2025

If any issues contact me at : [contact@aelof.com](mailto:contact@aelof.com)
I retaken the project with the agreement of Alisson Moretto.
