### ISSUE TITLE
ERROR - /root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Pinnacchio** [4w4k3/BeeLogger#105]
After entering my email and password the program gives the following error:
```
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 125, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory
```
The versions are:
- Kali Linux 2021.1
- Python 2.7.18
- Pyinstaller 4.3
- Wine 5.0.3

Please help me, I have tried them all but I can't solve this problem.
Thanks, Pinnacchio

**Comment by iEscapedVim** [comment]
open the install.sh and change `pyinstaller` to `pyinstaller==3.0`

**Comment by spyhunyter** [comment]
the solution you mention corrected the problem, another problem I have is that it does not send the emails, I already changed the permissions for applications in the mail destined for it

**Comment by teasimon** [comment]
> open the install.sh and change `pyinstaller` to `pyinstaller==3.0

**Cant open it could you please help?**

**Comment by lagrav** [comment]
i changed it to pyinstaller==3.0 but still getting the same error as the guy. what can i do about this, please help

**Comment by pecorhouse** [comment]
> i changed it to pyinstaller==3.0 but still getting the same error as the guy. what can i do about this, please help

Same. Can someone help?

**Comment by nehal-13** [comment]
> open the install.sh and change `pyinstaller` to `pyinstaller==3.0`

@YasirRWebDesigner  Thanks! This worked for me.

Detailed Steps for those who are facing same problem: 

Go inside the folder (BeeLogger-master ) and type:
`sudo vim install.sh`

after editing `pyinstaller` to `pyinstaller==3.0`
Save the file and **run Installer again**
`sudo ./install.sh`

Now run the beelogger by
`sudo python bee.py`

**Hope this helps :}**

**Comment by nehal-backspace** [comment]
> open the install.sh and change `pyinstaller` to `pyinstaller==3.0`

@YasirRWebDesigner Thanks! This worked for me.

Detailed Steps for those who are facing same problem:

Go inside the folder (BeeLogger-master ) and type:
`sudo vim install.sh` or `sudo nano install.sh`

after editing `pyinstaller` to `pyinstaller==3.0`  
(mind that there is no space in between anywhere in pyinstaller==3.0)
Save the file and **run Installer again**
`sudo ./install.sh`

Now run the beelogger by
`sudo python bee.py`

Hope this helps :}

**Comment by silkyearth** [comment]
> > open the install.sh and change `pyinstaller` to `pyinstaller==3.0`
> 
> @YasirRWebDesigner Thanks! This worked for me.
> 
> Detailed Steps for those who are facing same problem:
> 
> Go inside the folder (BeeLogger-master ) and type: `sudo vim install.sh` or `sudo nano install.sh`
> 
> after editing `pyinstaller` to `pyinstaller==3.0` (mind that there is no space in between anywhere in pyinstaller==3.0) Save the file and **run Installer again** `sudo ./install.sh`
> 
> Now run the beelogger by `sudo python bee.py`
> 
> Hope this helps :}

I tried that still doesn't work...

**Comment by osama-el-demerdash** [comment]
@Mrgadget23 
you can find the solution here in this video
https://www.youtube.com/watch?v=gwZFJzOBXoo&t=19s

**Comment by Bezdna7** [comment]
> open the install.sh and change `pyinstaller` to `pyinstaller==3.0`

How did you determine that this was the problem?
And thank you

**Comment by osama-el-demerdash** [comment]
what I understand is that pyinstaller is no longer available for python2
,so the link included with beelogger of pyinstaller does not work
you can sure by go to this path on you device:
/root/.wine/drive_c/Python27/Scripts/        ,my problem occurred because
pyinstaller.exe file which required by the tool does not exist in the path
after I installed the installer.sh I found it there and second problem that
the tool use pyinstaller-setup.py which does exist so I had to change it to
pyinstaller.exe which installer from installer.sh

‫في الاثنين، 25 أكتوبر 2021 في 11:53 ص تمت كتابة ما يلي بواسطة ‪Bezdna7‬‏ <‪
***@***.***‬‏>:‬

**Comment by ManosDuncan** [comment]
> 

i fcking love you, it worked perfectly thank you so much!!!!

**Comment by davideluna** [comment]
> @Mrgadget23 you can find the solution here in this video https://www.youtube.com/watch?v=gwZFJzOBXoo&t=19s

I was needing your video to solve the same problem here. I`m trying everything, but cannot solve :(

**Comment by Shtil0o0** [comment]
a have a problem after i change pyinstaller to pyinstaller==3.0: Could not fetch URL https://pypi.python.org/simple/pyinstaller/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping  Could not find a version that satisfies the requirement pyinstaller==3.0 (from versions: )No matching distribution found for pyinstaller==3.0

**Comment by rawandwrya** [comment]
> a have a problem after i change pyinstaller to pyinstaller==3.0: Could not fetch URL https://pypi.python.org/simple/pyinstaller/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping Could not find a version that satisfies the requirement pyinstaller==3.0 (from versions: )No matching distribution found for pyinstaller==3.0

@Shtil0o0 bypass the ssl certificate with adding --trusted-host to pyinstaller line in the install.sh file

wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller==3.0 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org

**Comment by Shtil0o0** [comment]
You are a genius. Thank you very much. You are the best

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did, and simple without bypass ssl cert !
With Python 3.13.7 @Pinnacchio @Shtil0o0 @davideluna @ManosDuncan @lagrav @teasimon 

It was tested on latest kali Linux 2025

If any issues contact me at : [contact@aelof.com](mailto:contact@aelof.com)
I retaken the project with the agreement of Alisson Moretto.
