### ISSUE TITLE
Gives me error on Kali linux when running ./install.sh

### ISSUE THREAD

**Issue by iqlessmemes** [4w4k3/BeeLogger#112]
sudo ./install.sh 
[sudo] password for kali: 
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://kali.download/kali kali-rolling InRelease [30.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Reading package lists... Done      
E: Release file for http://http.kali.org/kali/dists/kali-rolling/InRelease is not valid yet (invalid for another 2d 8h 59min 19s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 2d 15h 22min 25s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 2d 15h 23min 27s). Updates for this repository will not be applied.
./install.sh: 2: winecfg: not found
./install.sh: 3: wine: not found
./install.sh: 4: wine: not found
./install.sh: 5: wine: not found
./install.sh: 6: wine: not found

Anyone know what to do?

**Comment by Johnwick4567** [comment]
the wine package will automatically install, as here you don't have a wine package, but I cancelled the installation when it was installing into my machine because I don't know about wine package, if you know about it you can go through with it by
typing the command sudo apt-get install wine
I think it might help ya and I will come back to reply if it works with me.
good luck :)

**Comment by vipulraj01** [comment]
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 134, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory


It shows this after i've installed the wine

**Comment by vipulraj01** [comment]
It says to install wine32 .
but it gives error
![VirtualBox_Parrot_10_10_2022_09_40_55](https://user-images.githubusercontent.com/38418118/194798312-2bce7912-872f-41d3-8403-d175fdb47e07.png)
