### ISSUE TITLE
pyinstaller problem

### ISSUE THREAD

**Issue by User-790** [4w4k3/BeeLogger#115]
These info above are correct? (y/n) :y
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-scrip
t.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

First off great work love experimenting with the program and learning about it, secondly, I am not entirely understanding what exactly the issue above is. I have come to the conclusion that there is a problem with it installing the Fake file but I have no directory assigned? 
Any suggestion I am very lost.

**Comment by DallasMcCarver** [comment]
I have the same issue, any news or workarounds? Thanks

**Comment by iczopl1** [comment]
wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller==3.6
This command use and beloger is instalet suscesful

**Comment by Syirasky** [comment]
Have u tried to install another python version?

https://github.com/Syirasky/BeeLogger#running-for-backbox-os-edited-by-syirasky

https://github.com/Syirasky/BeeLogger/blob/Syirasky-patch-1/backboxinstallscripts.sh

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
@iczopl1 @Syirasky @DallasMcCarver @User-790 fixed all problem !!!
