### ISSUE TITLE
Error and can't figure out why

### ISSUE THREAD

**Issue by soppaz** [4w4k3/BeeLogger#30]
Hello, I keep getting this error. Any idea how to fix?

These info above are correct? (y/n) :y
125 INFO: PyInstaller: 3.2.1
126 INFO: Python: 2.7.12
126 INFO: Platform: Windows-7-6.1.7601-SP1
127 INFO: wrote H:\Ty÷p÷ytõ\BEEL~XZC\k.spec
133 INFO: UPX is not available.
134 INFO: Extending PYTHONPATH with paths
['H:\\Ty\xf6p\xf6yt\xe4\\BeeLogger', 'H:\\Ty\xf6p\xf6yt\xe4\\BEEL~XZC']
136 INFO: checking Analysis
137 INFO: Building Analysis because out00-Analysis.toc is non existent
138 INFO: Initializing module dependency graph...
142 INFO: Initializing module graph hooks...
184 INFO: running Analysis out00-Analysis.toc
187 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe
191 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
193 WARNING: Assembly not found
193 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
230 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
232 WARNING: Assembly not found
232 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
288 INFO: Caching module hooks...
293 INFO: Analyzing H:\Ty÷p÷ytõ\BeeLogger\k.py
1712 INFO: Processing pre-safe import module hook   win32com
2322 INFO: Processing pre-find module path hook   distutils
2423 INFO: Loading module hooks...
2424 INFO: Loading module hook "hook-distutils.py"...
2425 INFO: Loading module hook "hook-httplib.py"...
2426 INFO: Loading module hook "hook-pywintypes.py"...
2680 INFO: Loading module hook "hook-encodings.py"...
3161 INFO: Loading module hook "hook-win32com.py"...
3221 INFO: Loading module hook "hook-pythoncom.py"...
3484 INFO: Looking for ctypes DLLs
3484 INFO: Analyzing run-time hooks ...
3486 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
3492 INFO: Looking for dynamic libraries
3668 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3669 WARNING: Assembly not found
3670 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
3673 INFO: Searching for assembly x86_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3674 INFO: Found manifest C:\Python27\lib\site-packages\Pythonwin\Microsoft.VC90.MFC.manifest
3676 INFO: Searching for file mfc90.dll
3677 INFO: Found file C:\Python27\lib\site-packages\Pythonwin\mfc90.dll
3678 INFO: Searching for file mfc90u.dll
3679 INFO: Found file C:\Python27\lib\site-packages\Pythonwin\mfc90u.dll
3680 INFO: Searching for file mfcm90.dll
3680 INFO: Found file C:\Python27\lib\site-packages\Pythonwin\mfcm90.dll
3680 INFO: Searching for file mfcm90u.dll
3682 INFO: Found file C:\Python27\lib\site-packages\Pythonwin\mfcm90u.dll
3684 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 21022, 8)
3761 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3762 WARNING: Assembly not found
3763 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
3812 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3814 WARNING: Assembly not found
3814 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
3841 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3842 WARNING: Assembly not found
3842 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
3965 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3966 WARNING: Assembly not found
3967 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
4032 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
4034 WARNING: Assembly not found
4035 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
4068 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
4069 WARNING: Assembly not found
4070 ERROR: Assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none not found
4142 INFO: Looking for eggs
4142 INFO: Using Python library C:\Python27\python27.dll
4143 INFO: Found binding redirects: 
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 21022, 8), publicKeyToken=u'1fc8b3b9a1e18e3b')]
4147 INFO: Warnings written to H:\Ty÷p÷ytõ\BEEL~XZC\build\k\warnk.txt
4201 INFO: checking PYZ
4202 INFO: Building PYZ because out00-PYZ.toc is non existent
4202 INFO: Building PYZ (ZlibArchive) H:\Ty÷p÷ytõ\BEEL~XZC\build\k\out00-PYZ.pyz
4575 INFO: Building PYZ (ZlibArchive) H:\Ty÷p÷ytõ\BEEL~XZC\build\k\out00-PYZ.pyz completed successfully.
Traceback (most recent call last):
  File "/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\api.py", line 388, in __init__
    self.console, self.uac_admin, self.uac_uiaccess)
  File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1051, in create_manifest
    depmanifest = ManifestFromXMLFile(filename)
  File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 999, in ManifestFromXMLFile
    manifest.parse(filename_or_file)
  File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 753, in parse
    self.load_dom(domtree, False)
  File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 721, in load_dom
    (self.filename, manifest.name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Please clone now and install again

**Comment by soppaz** [comment]
I did that and now the errors are https://pastebin.com/R1YhUe48
