### ISSUE TITLE
Wine32 Error

### ISSUE THREAD

**Issue by gpimentelv** [4w4k3/BeeLogger#36]
While Running **./install.sh**

E: No se ha podido localizar el paquete wine32
/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")
/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")
/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")
/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")
/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")

Later, when i open Bee.py **python bee.py**

Went through the process, at the last step (**Input Mail and Password**)

/usr/bin/wine: 1: /usr/bin/wine: Syntax error: word unexpected (expecting ")")
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 143, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**I'M UNDER UBUNTU BASH ON WINDOWS 10 LINUX SUBSYSTEM**

**Comment by gpimentelv** [comment]
**[SOLVED]**

**NEW LINES BEFORE**
→ sudo su
→ sudo dpkg --add-architecture i386
→ sudo apt-get update
→ sudo apt-get install wine -y
→ sudo apt-get install wine32 -y
→ sudo apt-get install git (por si no tienen git instalado/actualizado)

**THEN**
→ git clone https://github.com/4w4k3/BeeLogger.git
→ cd BeeLogger
→ sudo su
→ chmod +x install.sh
→ ./install.sh
→ WAIT....
→ python bee.py

**TESTED ON UBUNTU 14.04 X86**
