### ISSUE TITLE
wine: cannot find '/root/.wine/drive_c/Python27/python.exe

### ISSUE THREAD

**Issue by zerolshen** [4w4k3/BeeLogger#39]
Error message:

wine: cannot find '/root/.wine/drive_c/Python27/python.exe

Does not install pywin32-220

http://imgur.com/jCcuDMm

Python 2.7.12

**Comment by ubaidahmad007** [comment]
me also have  same issue

**Comment by zerolshen** [comment]
I solved it the same day xD!

Is pywin32-220 for x64bits xD!

**Comment by 4w4k3** [comment]
@zerolshen What you've do to solve?

**Comment by Kuhakanu** [comment]
Got the same issue here as well :/ tried to clone again but same results, any solutions?

**Comment by zerolshen** [comment]
All x64bits, Force Install Python with Wine

**Comment by zerolshen** [comment]
Install "git". To use the "git" command

**Comment by Kuhakanu** [comment]
Sorry, I'm still kinda new to this, could you explain how or give a link to a video where it shows me how to do it?

**Comment by 4w4k3** [comment]
Don't cancel the system upgrade. Run ./install.sh

**Comment by Kuhakanu** [comment]
I tried and it's still the same thing. Maybe you can see what I'm doing wrong here.
W: Target DEP-11-icons (non-free/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:12 and /etc/apt/sources.list:17
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\ensurepip\__init__.py", line 9, in <module>
    import tempfile
  File "C:\Python27\lib\tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "C:\Python27\lib\random.py", line 885, in <module>
    _inst = Random()
  File "C:\Python27\lib\random.py", line 97, in __init__
    self.seed(x)
  File "C:\Python27\lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
err:msi:ITERATE_Actions Execution halted, action L"UpdatePip" returned 1627
err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1627

**Comment by Jnrmax202017** [comment]
i have the same problem :( 

File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
mod_name, _Error)
File "C:\Python27\lib\runpy.py", line 111, in get_module_details
import(mod_name) # Do not catch exceptions initializing package
File "C:\Python27\lib\ensurepip_init.py", line 9, in 
import tempfile
File "C:\Python27\lib\tempfile.py", line 35, in 
from random import Random as _Random
File "C:\Python27\lib\random.py", line 885, in 
_inst = Random()
File "C:\Python27\lib\random.py", line 97, in init
self.seed(x)
File "C:\Python27\lib\random.py", line 113, in seed
a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
err:msi:ITERATE_Actions Execution halted, action L"UpdatePip" returned 1627
err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1627

Someone can help us? :c

**Comment by 5p00ks** [comment]
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Same problem, looking for a fix. I've tried a lot of apt-gets, updates and upgrades, etc.
