### ISSUE TITLE
Hey, i have a problem with BeeLogger

### ISSUE THREAD

**Issue by Yuzuke28** [4w4k3/BeeLogger#40]
This is my problem
ine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 134, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

sorry, i'm brazilian my english is bad

**Comment by 4w4k3** [comment]
Hi, Please type "uname -a" and send me output.
Send me an email if you wanna an quick answer.

**Comment by krampus0101** [comment]
turn on terminal
get on .../Desktop/BeeLogger/
write ls
write ./install.sh 
or 
python ./install.sh
it should help
check
write python bee.py

**Comment by tomasmotadelcampo** [comment]
@krampus0101  excellent contribution, thank you. Greetings from Central America
