### ISSUE TITLE
Problem with BeeLogger

### ISSUE THREAD

**Issue by iFireTech** [4w4k3/BeeLogger#41]
This is my problem
sh: 1: wine: not found
Traceback (most recent call last):
File "bee.py", line 161, in 
main()
File "bee.py", line 134, in main
os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by UndeadSec** [comment]
Probably you don't have the repo.
See: https://docs.kali.org/general-use/kali-linux-sources-list-repositories
