### ISSUE TITLE
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': 

### ISSUE THREAD

**Issue by sapan2856** [4w4k3/BeeLogger#56]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 125, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

After running python bee.py,i got the above error.Please help me to solve this error

**Comment by ashutosh4336** [comment]
Same problem anyone hero to help kindly give it a minute to help

**Comment by Syirasky** [comment]
.wine folder does not exist . 
You can reinstall ur wine or use my install script from my beelogger repo

**Comment by wirdfire** [comment]
got the same issue. keep getting annoying feedback 


These info above are correct? (y/n) :y
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 107, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by wirdfire** [comment]
@sapan2856 were you able to solve your problem?? How did you do that please share. i am kinda stock with this.....thanks

**Comment by sapan2856** [comment]
@wirdfire did you solve the problem. If not then could you post/show  source.list repo... You can dm me on fb at sapan.rn43@gmail.com..

**Comment by Foysal2005** [comment]
i have also face this problem..

**Comment by Googlecode13** [comment]
@sapan2856 did u find out how to fix it?

**Comment by maroc46** [comment]
have the same problem 
-.- and i see the repo is from 2017 
is here anywhere and have fix the problem^

**Comment by viveksinghrajawat** [comment]
its is akward but i recommend you to try this 
step 1 :https://github.com/z00z/ZLogger
make a clone of this git
step2: cd zlogger
step3: bash ./install.sh
now run beelogger 
enjoy

**Comment by NoKangaroo1** [comment]
I cant find dist/Bee.exe

**Comment by osama-el-demerdash** [comment]
@sapan2856 @ashutosh4336  watch this video I hope help you
https://www.youtube.com/watch?v=gwZFJzOBXoo&t=19s

**Comment by SamEerDark** [comment]
> 
> 
> @sapan2856 @ashutosh4336 watch this video I hope help you https://www.youtube.com/watch?v=gwZFJzOBXoo&t=19s

Not working after trying the steps

**Comment by osama-el-demerdash** [comment]
could you send me screenshot for the problem in terminal

‫في الأحد، 31 أكتوبر 2021 في 12:40 ص تمت كتابة ما يلي بواسطة ‪SamEerDark‬‏
***@***.***‬‏>:‬

**Comment by osama-el-demerdash** [comment]
if you need keylogger from the tool you could create a new gmail account
and send me the name and password ,I will make a keyogger and send it for
you if it tool does not work

‫في السبت، 6 نوفمبر 2021 في 5:16 ص تمت كتابة ما يلي بواسطة ‪osama kort‬‏ <‪
***@***.***‬‏>:‬

**Comment by nocul33** [comment]
@osama-el-demerdash I have the same problem, will you help me
