### ISSUE TITLE
Error, please help.

### ISSUE THREAD

**Issue by david666z** [4w4k3/BeeLogger#65]
this is the error, please give a minute to help.

wine : cannot find '/root/.wine/drive_c/Python27/python.exe
Traceback (most recent call last):
    File "bee.py", line 161, in <module>
        main()
    File "bee.py", line 134, in main
        os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by Syirasky** [comment]
pls view my repository. 
or u can do it by urself, all it need is just latest wine from winehq and some directory fix.

**Comment by MUWASEC** [comment]
is this link work ???
https://github.com/Syirasky/BeeLogger

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @MUWASEC @Syirasky @david666z 

It was tested on latest kali Linux 2025

If any issues contact me at : contact@aelof.com
I retaken the project with the agreement of Alisson Moretto.
