### ISSUE TITLE
bee.py error help me

### ISSUE THREAD

**Issue by raiainakabena** [4w4k3/BeeLogger#69]
$ python bee.py
Traceback (most recent call last):
  File "bee.py", line 11, in <module>
    if not os.geteuid() == 0:
AttributeError: 'module' object has no attribute 'geteuid'

What is the solution?

operating system is window

**Comment by doctorparadoxx** [comment]
Please can you try this $ python2.7 bee.py

**Comment by mahesh1706** [comment]
These info above are correct? (y/n) :y
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 97, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory
                                                                      

help me pls

**Comment by mahesh1706** [comment]
I am using kali Linux
