### ISSUE TITLE
4w4k3

### ISSUE THREAD

**Issue by 4FR41D** [4w4k3/BeeLogger#74]
is:issue is:open File "C:\Python27\lib\site-packages\PyInstaller\building\api.py", line 397, in __init__     self.console, self.uac_admin, self.uac_uiaccess)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1051, in create_manifest     depmanifest = ManifestFromXMLFile(filename)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 999, in Manifis:issue is:open File "C:\Python27\lib\site-packages\PyInstaller\building\api.py", line 397, in __init__     self.console, self.uac_admin, self.uac_uiaccess)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1051, in create_manifest     depmanifest = ManifestFromXMLFile(filename)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 999, in ManifestFromXMLFile     manifest.parse(filename_or_file)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 753, in parse     self.load_dom(domtree, False)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 721, in load_dom     (self.filename, manifest.name)) UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 12: ordinal not in range(128) Traceback (most recent call last):   File "bee.py", line 167, in <module>     main()   File "bee.py", line 113, in main     os.rename('dist/k.exe', 'dist/' + name) OSError: [Errno 2] No such file ordirectoryestFromXMLFile     manifest.parse(filename_or_file)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 753, in parse     self.load_dom(domtree, False)   File "C:\Python27\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 721, in load_dom     (self.filename, manifest.name)) UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 12: ordinal not in range(128) Traceback (most recent call last):   File "bee.py", line 167, in <module>     main()   File "bee.py", line 113, in main     os.rename('dist/k.exe', 'dist/' + name) OSError: [Errno 2] No such file ordirectory

**Comment by WrongProgram1** [comment]
Mine is Failed To Execute Script log
