### ISSUE TITLE
BeeLogger ERROR

### ISSUE THREAD

**Issue by cyberpurple** [4w4k3/BeeLogger#82]
**After i type e-mail and password  i get thi**s : 
These info above are correct? (y/n) :y
/usr/bin/wine: 40: exec: /usr/lib/wine/wine: Exec format error
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 107, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

Please guys someon help me i'm trying to fix this for 2 days and still not luck.

**Comment by Chandraditya-Singh-Sikarwar** [comment]
Anyone got solution ?
