### ISSUE TITLE
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'

### ISSUE THREAD

**Issue by 5p00ks** [4w4k3/BeeLogger#83]
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Same problem, looking for a fix. I've tried a lot of apt-gets, updates and upgrades, etc.

_Originally posted by @5p00ks in https://github.com/4w4k3/BeeLogger/issues/39#issuecomment-521161759_

**Comment by 5p00ks** [comment]
- **While running ./install.sh**
https://imgur.com/gallery/GABMQtF


- **-After giving e-mail data**
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 107, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory


![bug1beelogger](https://user-images.githubusercontent.com/54100230/63021068-0b96fc80-bea0-11e9-9037-bf187830ae76.png)
![bug2](https://user-images.githubusercontent.com/54100230/63021069-0b96fc80-bea0-11e9-87bf-09480d4869c3.png)

**Comment by butch3r007** [comment]
### [Fixed]
just do whatever this guy do in this video and it will be fixed it worked for me anyway

[youtube sh4dy](https://www.youtube.com/watch?v=zTBl2vjx9j4)

i hope this work for you too

**Comment by PAWEAOAKF** [comment]
Can no longer be seen :c

**Comment by Tanyike** [comment]
video is private please can you list the steps

**Comment by Oluwaseunoa** [comment]
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Kindly help with the steps

**Comment by Chandraditya-Singh-Sikarwar** [comment]
Anyone please help!

**Comment by svistiik** [comment]
need help with this too
