### ISSUE TITLE
i have this problem how can solve?

### ISSUE THREAD

**Issue by ghost** [4w4k3/BeeLogger#92]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by cyberpurple** [comment]
Those lazy tools ain’t working anymore. You should go deeper if you what I
mean.
Cheers ✌️

**Comment by slipknot64** [comment]
The reason being is due to the fact when it tries to install pyinstaller it get's the new version of pyinstaller but because the new version does not support python 2.7 you have to instead use an old pyinstaller for example pip install pyinstaller==2.1 try that and if it doesn't work go to /root/.wine/drive_c/Python27/Scripts/  directory and open command prompt there and try again after that all should be good

**Comment by dustin1619987** [comment]
Deeper as in where lol. Got any suggestions for other tools like this???
