### ISSUE TITLE
bee.py line 20

### ISSUE THREAD

**Issue by Night-Hawk7** [4w4k3/BeeLogger#93]
In line 20: print '\n'
and then it tells me: SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\n')?
NEED HELP

**Comment by agam778** [comment]
Same problem with me. Please Help!!!!!!

**Comment by chickennugge321** [comment]
Hi, so I am not 100% sure this will work but it did for me, try writing: "python2 bee.py" If this does not work try typing in a separate terminal: "sudo apt install python2" and then type: "python2 bee.py"

**Comment by Vjstyles12** [comment]
It's working bro

**Comment by jack4770** [comment]
run with python2 it will work

**Comment by varification23** [comment]
These info above are correct? (y/n) :y
sh: line 1: wine: command not found
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory
