### ISSUE TITLE
bee.py problem

### ISSUE THREAD

**Issue by chickennugge321** [4w4k3/BeeLogger#94]
Hi so whenever it asks me if my gmail info is correct, it gives me this:

C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 97, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

Can someone please help?

**Comment by Vico1204** [comment]
I have the same issue

**Comment by ghost** [comment]
Yeah me too
Any suggestions?

**Comment by deeplinux2003** [comment]
same problem pls help somebody ......    
:(

**Comment by Chandraditya-Singh-Sikarwar** [comment]
Please anyone help to solve issue .........

**Comment by Ziaglaa** [comment]
I also have the same Issue

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @Ziaglaa @Chandraditya-Singh-Sikarwar @ghost @chickennugge321 @Vico1204 @deeplinux2003 

It was tested on latest kali Linux 2025

If any issues contact me at : contact@aelof.com
I retaken the project with the agreement of Alisson Moretto.
