### ISSUE TITLE
Having issue installing python :  /install.sh 

### ISSUE THREAD

**Issue by dustin1619987** [4w4k3/BeeLogger#96]
These info above are correct? (y/n) :y
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 107, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory
root@kali:~/BeeLogger# 

./install.sh 
-> Trys to download python in wine but never works. I did see a video on you-tube with this dude fixing it but I could not understand a single thing he was saying // but did understand mostly on how he fixed it but was having trouble on the way he did it. I'm going to try and watch that video again and see if I can fix this issue. 

Can't figure out of the fix this issue. I know ti is dealing with the python not being able to download correctly. Any solutions. The solutions provided in the other Issue didn't work for me. I have try multiple things but can't get the python2.7 to download. 

![Screenshot_2021-03-08_20-16-40](https://user-images.githubusercontent.com/68936871/110403606-64fae980-804b-11eb-9d98-75fda1cdeef1.png)

![Screenshot_2021-03-08_20-17-09](https://user-images.githubusercontent.com/68936871/110403608-64fae980-804b-11eb-9c48-f222f8b743e4.png)

![Screenshot_2021-03-08_20-17-29](https://user-images.githubusercontent.com/68936871/110403609-64fae980-804b-11eb-82d7-0e09dd1228e6.png)

Has anyone figured out on how to fix this? If not got any suggestion on other programs that do what BeeLogger
 does. Thank you!

**Comment by adropofliquid** [comment]
Try to install python again. But when the dialog shows up. Select "Install just for me"

**Comment by fox121212** [comment]
> Try to install python again. But when the dialog shows up. Select "Install just for me"

didnt work for me any other thing i can do?

**Comment by dustin1619987** [comment]
Still having trouble lol

**Comment by adropofliquid** [comment]
> Still having trouble lol

are u still having the same issue?

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @adropofliquid @dustin1619987 @fox121212 

It was tested on latest kali Linux 2025

If any issues contact me at : contact@aelof.com
I retaken the project with the agreement of Alisson Moretto.
