### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by ghost** [4w4k3/BeeLogger#98]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory                                                                                                   
Traceback (most recent call last):                                                                                    
  File "bee.py", line 161, in <module>                                                                                
    main()                                                                                                            
  File "bee.py", line 116, in main                                                                                    
    os.rename('dist/k.exe', 'dist/' + name)                                                                           
OSError: [Errno 2] No such file or directory

**Comment by Chandraditya-Singh-Sikarwar** [comment]
I have same issue please help .........

**Comment by g0dsito** [comment]
Bros you need to install wine and use it in kali virtual machine is better

**Comment by ghost** [comment]
These info above are correct? (y/n) :y
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 116, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by S2GtheCreator** [comment]
waiting for a solution

**Comment by DallasMcCarver** [comment]
I have same issue and i have installed wine , any solutions?

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @DallasMcCarver @S2GtheCreator @g0dsito @Chandraditya-Singh-Sikarwar 

It was tested on latest kali Linux 2025

If any issues contact me at : contact@aelof.com
I retaken the project with the agreement of Alisson Moretto.
