### ISSUE TITLE
Hi Please Help

### ISSUE THREAD

**Issue by frl12** [4w4k3/BeeLogger#99]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 143, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by OpenSkillFactory** [comment]
The new Beelogger working in 2025 :
https://github.com/OpenSkillFactory/Beelogger

Don't hesitate to share, you'll also find a video on my Youtube channel to see how i did !
With Python 3.13.7 @frl12 

It was tested on latest kali Linux 2025

If any issues contact me at : contact@aelof.com
I retaken the project with the agreement of Alisson Moretto.
